# Generated by Django 4.0.5 on 2022-07-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('agen_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=11)),
                ('servico', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=20)),
            ],
        ),
    ]
